## List of files and params to be used in the analysis

# Fasta files
ensembl:
  canonical.fasta
fomonet:
  fomonet.fasta

# Path to DIA-NN executable
diann_path:
  /usr/diann/1.8.1/diann-1.8.1

# Path to ThermoRawFileParser executable
thermorawfileparser_path:
  ~/ThermoRawFileParser1.4.2/ThermoRawFileParser.exe

# List of conditions names. Will be used to determine which files belong to 
# which condition.  
conditions:
  - ctr
  - hyp
  - rep

replicates:
  [1, 2, 3, 4, 5, 6, 7, 8]

# Maximum number of replicates without quantification allowed to consider a 
# protein group as confidently quantified
allowed_na:
  0